accelerate launch --mixed_precision=no /home/zabibeau/DeepLearningProject/lora-factorized/train_text_to_image_lora.py \
  --pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5 \
  --dataset_name=YaYaB/onepiece-blip-captions \
  --dataloader_num_workers=8 \
  --resolution=512 \
  --center_crop \
  --random_flip \
  --train_batch_size=4 \
  --gradient_accumulation_steps=4 \
  --max_train_steps=2000 \
  --learning_rate=1e-04 \
  --max_grad_norm=1 \
  --lr_scheduler=cosine \
  --lr_warmup_steps=0 \
  --output_dir=/home/zabibeau/DeepLearningProject/lora-factorized/regular_outputs \
  --push_to_hub \
  --hub_model_id=onepiece-lora \
  --report_to=wandb \
  --checkpointing_steps=500 \
  --validation_prompt="A man with a sword in One Piece" \
  --seed=1337